version: "3.7"

services:
  db:
    image: postgres:13.0-alpine
    container_name: postgres_container
    env_file:
      - project/backend/.env-non-dev
    networks:
      - postgres
    ports:
      - "2344:5432"

  app:
    build:
      context: project/backend
    env_file:
      - project/backend/.env-non-dev
    container_name: fastapi_container
    restart: always
    command: ["deploy/app.sh"]
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - postgres
  pgadmin:
    container_name: pgadmin_container
    restart: always
    image: dpage/pgadmin4
    depends_on:
      - db
    env_file:
      - project/backend/.env-non-dev
    networks:
      - postgres
    ports:
      - "5050:80"
    platform: linux/amd64


networks:
  postgres:
    driver: bridge