version: "3.8"

services:
#TODO: change db

  # db:
  #   container_name: postgres_container
  #   image: postgres:13.0-alpine
  #   environment:
  #     - "POSTGRES_HOST_AUTH_METHOD=trust"
  #   networks:
  #     - project-network

  backend:
    container_name: backend
    build:
      context: project/backend
    # restart: always
    command: /prod.sh
    # depends_on:
    #   - db
    networks:
      - project-network
    volumes:
      - ./project/backend:/code
      - static:/code/static
      - media:/code/media

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/dev/Dockerfile
    # restart: always
    ports:
      - "81:80"
    depends_on:
      - backend
    
    volumes:
      - static:/usr/src/app/static
      - media:/usr/src/app/media

    networks:
      - project-network

volumes:
  static:
  media:

networks:
  project-network:
    driver: bridge