version: "3.8"

services:
#TODO: change db
  # db:
  #   container_name: postgres_container
  #   image: postgres:13.0-alpine
  #   environment:
  #     - "POSTGRES_HOST_AUTH_METHOD=trust"
  #   networks:
  #     - project-network



  backend:
    container_name: backend
    build:
      context: project/backend
    restart: always
    command: /start_prod.sh
    # depends_on:
    #   - db
    networks:
      - project-network
    volumes:
      - ./project/backend:/code
      - static:/code/static
      - media:/code/media


  frontend:
    container_name: frontend
    build:
      context: ./project/frontend
    volumes:
      - ./project/frontend:/app/:ro
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - project-network
    environment:
      - NODE_ENV=development
  
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: dev-front/Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    
    volumes:
      - static:/usr/src/app/static
      - media:/usr/src/app/media

    networks:
      - project-network


volumes:
  static:
  media:


networks:
  project-network:
    driver: bridge